### Create
POST http://localhost:8000/book/create
Content-Type: application/json

{
    "code": "book 1",
    "topicName": "topic 1",
    "categoryName": "category 1",
    "name": "Toán 10",
    "image": "Create a new image",
    "author": "Duy Lam",
    "language": "Tiếng Việt",
    "publishingCompany": "Create a new publishing company",
    "releaseDate": "7/8/2022",
    "numberOfPages": 100,
    "location": "Create a new location",
    "borrowCount": 0,
    "status": false
}

### Read One
GET http://localhost:8000/book/readOne
Content-Type: application/json

{
    "code": "book 1"
}

### Read All
GET http://localhost:8000/book/readAll
Content-Type: application/json

### Update
POST http://localhost:8000/book/update
Content-Type: application/json

{
    "code": "book 1",
    "topicName": "topic 1",
    "categoryName": "category 1",
    "name": "Toán 12",
    "image": "Create a new image",
    "author": "Duy Lam",
    "language": "Tiếng Việt",
    "publishingCompany": "Trà Vinh",
    "releaseDate": "7/8/2022",
    "numberOfPages": 99,
    "location": "Trà Vinh",
    "borrowCount": 4,
    "status": "Nguyên vẹn"
}

### Delete One
POST http://localhost:8000/book/deleteOne
Content-Type: application/json

{
    "code": "book 1đ"
}

### Delete All
POST http://localhost:8000/book/deleteAll
Content-Type: application/json
